<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\CogentCode.Template.Domain\CogentCode.Template.Domain.csproj" />
  </ItemGroup>

</Project>
